// ignore_for_file: constant_identifier_names

const String NO_INTERNET = 'لطفا اتصال به اینترنت را بررسی کنید.'; //todo
const String SERVER_ERROR = 'مشکلی پیش آمده است، لطفا بعدا تلاش کنید.'; //todo
const String OTP_ERROR = 'کد تایید وارد شده صحیح نمی باشد';
const String TRY_AGAIN_TEXT = 'تلاش مجدد';
const String CONTACT_US_TEXT = 'تماس با پشتیبانی';
const String CONTACT_US_NUMBER = '09100045125';
const String FORBIDDEN_TEXT =
    'کاربر گرامی به دلایل امنیتی حساب شما مسدود شده است.';
const String PHONE_NUMBER_LABEL = 'لطفا شماره همراه خود را وارد کنید'; //todo
const String PHONE_NUMBER_HINT = '۰۹۱۲۱۲۳۴۵۶۷'; //todo
const String PHONE_NUMBER_BUTTON = 'دریافت کد'; //todo
const String PHONE_NUMBER_AGREEMENT_1 = 'ورود شما به معنای پذیرش '; //todo
const String PHONE_NUMBER_AGREEMENT_2 = 'توافقنامه کاربری'; //todo
const String PHONE_NUMBER_AGREEMENT_3 = ' است.'; //todo
const String PHONE_NUMBER_NOT_VALID =
    'لطفا شماره موبایل را صحیح وارد کنید.'; //todo
const String NATIONAL_ID_NOT_VALID = 'لطفا کد ملی را صحیح وارد کنید'; //todo
const String EMAIL_NOT_VALID = 'لطفا ایمیل را صحیح وارد کنید';
const String AMOUNT_IS_EMPTY = 'لطفا مبلغ مورد نظر را وارد نمایید.'; //todo۱
const String PHONE_NUMBER_IS_EMPTY = 'لطفا شماره موبایل را وارد نمایید'; //todo
const String DATA_NOT_AVAILABLE = 'محتوای ذخیره شده ای وجود ندارد.'; //todo
const String VERIFY_CODE_LABEL_1 = 'کد تایید ارسال شده به شماره  ';
const String VERIFY_CODE_LABEL_2 = ' را وارد کنید';
const String VERIFY_CODE_HINT = '۱۲۳۴۵۶';
const String VERIFY_CODE_BUTTON = 'تایید';
const String RESEND_CODE_TEXT = 'دوباره پیامک فعال‌سازی ارسال شود؟';
const String CHANGE_PHONE_NUMBER = 'شماره را اشتباه وارد کردید؟';
const String WRONG_NUMBER_LENGTH = 'شماره موبایل باید 11 رقم باشد';
const String WRONG_NUMBER_START = 'شماره موبایل باید با 09 شروع شود';
const String VERIFY_CODE_IS_INVALID = 'کد تایید وارد شده صحیح نمی‌باشد.';
const String VERIFY_CODE_IS_EMPTY = 'کد تایید را وارد کنید.';
const String HOME_LABEL = 'خانه';
const String SERVICES_LABEL = 'سرویس‌ها';
const String PROFILE_LABEL = 'حساب کاربری';
const String LAST_TRANSACTIONS_LABEL = 'آخرین تراکنش‌ها';
const String DO_FIRST_TRANSACTIONS = 'اولین تراکنش خود را انجام دهید.';
const String PAY_THE_BILL_TEXT = 'پرداخت قبض';
const String DATE_TEXT = '۲۰:۴۵  ۱۴/۰۲/۱۲';
const String NO_ITEM_TEXT = 'هنوز تراکنشی انجام نشده است!';
const String NO_INTERNET_SPLASH = 'لطفا اتصال به اینترنت را بررسی کنید.';
const String FORCE_UPDATE = 'نسخه جدید وی‌بانک آماده است.';
const String IRANCELL = 'ایرانسل';
const String RIGHTEL = 'رایتل';
const String HAMRAH_AVAL = 'همراه اول';
const String PROFILE_DETAIL_LABEL = 'پروفایل کاربر';
const String PROFILE_FINANCE_LABEL = 'پروفایل مالی';
const String WALLET_LABEL = 'کیف پول';
const String CARD_MANAGE_LABEL = 'مدیریت کارت';
const String TRANSACTIONS_LABEL = 'لیست تراکنش‌ها';
const String LOG_OUT_LABEL = 'خروج از حساب کاربری';
const String PROFILE_FRIENDS_LABEL = 'دعوت دوستان';
const String PROFILE_NOTIFICATION_LABEL = 'اعلانات';
const String PROFILE_SETTING_LABEL = 'تنظیمات';
const String PROFILE_SUPPORT_LABEL = 'پشتیبانی';
const String PROFILE_ABOUT_LABEL = 'درباره ما';
const String PROFILE_NAME_HINT = 'نام و نام خانوادگی';
const String PROFILE_DOB_HINT = 'تاریخ تولد';
const String PROFILE_NATIONAL_HINT = 'کد ملی';
const String PROFILE_GENDER_HINT = 'جنسیت';
const String PROFILE_ADDRESS_HINT = 'محل سکونت';
const String PROFILE_EMAIL_HINT = 'ایمیل';
const String EMPTY_AMOUNT = 'لطفا مبلغ را وارد کنید.';
const String VIE_BANK_EMAIL_HINT = 'info@viepay.ir' ;
const String SEARCH = 'جستجو';
const String VIEW_MORE = 'مشاهده بیشتر';
const String SELECT = 'انتخاب';
const String SELECT_LOC = 'محل دریافت خودرو را انتخاب کنید';
const String NAME = 'نام';
const String LAST_NAME = 'نام خانوادگی';
const String PHONE_NO = 'شماره همراه';
const String TOURISM = 'گردشگری';
const String RENT_CAR = 'کرایه خودرو';
const String RENT_CAR_HISTORY = 'سوابق کرایه خودرو';
const String RENT_CAR_TR = 'کرایه خودرو در ترکیه';
const String CAR_SELECT_LOCATION = 'انتخاب محل دریافت خودرو';
const String CAR_SEL_LOC = 'لطفا محل دریافت خودرو را انتخاب کنید';
const String DELIVERY_IN_AIRPORT_PRICE = 'تحویل در فرودگاه ها (300 لیر)';
const String SHOW_CARS = 'نمایش خودرو ها';
const String CAR_DETAIL = 'جزئیات خودرو';
const String PROPERTY = 'ویژگی ها';
const String INS_PRICE = 'قیمت بیمه:';
const String TL_UNIT = 'لیر';
const String AGREEMENT = 'توافقنامه';
const String AGREEMENT_ACC = 'پذیرفتم';
const String FROM_DATE = 'از تاریخ: ';
const String TO_DATE = 'تا تاریخ: ';
const String SUBMIT = 'ثبت';
const String DESC = 'شرح';
const String TOTAL_PRICE = 'مبلغ کل:';
const String SPECIAL_DELIVERY_PRICE = 'قیمت تحویل اختصاصی:';
const String PRICE = 'مبلغ';
const String FREE = 'رایگان';
const String PAYMENT_TYPE = 'نحوه پرداخت';
const String PAYMENT_TYPE_SEL = 'نحوه پرداخت را انتخاب کنید';
const String WALLET_CREDIT_ABSENCE = 'موجودی کیف پول کافی نیست.';
const String TIME_DATE = 'تاریخ و ساعت:';
const String TRACKING_NO = 'شماره پیگیری:';
const String SUPPORT_IRAN = 'شماره پشتیبانی ایران:';
const String SUPPORT_TR = 'شماره پشتیبانی ترکیه(واتساپ):';
const String DELIVERY_LOC = 'محل تحویل:';
const String RE_SEARCH = 'جستجو مجدد';

const String NO_CAR_RENT = 'در تاریخ انتخابی، خودرویی برای نمایش وجود ندارد!';
const String INVALID_DATE = 'لطفا تاریخ انتخابی را صحیح وارد کنید';

const String SITE_URL = 'https://sabokbar_d.ir';
const String WE_ARE_VIE = 'WE ARE VIE';

const String USER_AGREEMENT = 'توافقنامه کاربری';
const String QUESTIONS = 'سوالات متداول';
const String CONTACT_US = 'تماس با ما';
const String SELECT_DEPARTMENT = 'انتخاب واحد';
const String PLZ_SELECT_DEPARTMENT = 'واحد را انتخاب کنید';
const String TYPE_MSG = '...پیام خود را تایپ کنید';
const String SEND_MSG = 'ارسال پیام';
const String SEND_MSG_SUCCESS = 'پیام شما با موفقیت ارسال شد.';
const String SEND_MSG_FAIL = 'در حال حاضر امکان ارسال پیام شما وجود ندارد.';
const String APP_MODE = 'حالت نمایش وی‌بانک';
const String PASS_WORD = 'رمز ورود';
const String RE_PASS_WORD = 'تکرار رمز ورود';
const String FINGER_PRINT_LOGIN = 'ورود با اثر انگشت';
const String PASS_CONDITION = 'شامل حداقل یک حرف کوچک و بزرگ انگلیسی';

const String PASS_CONDITION_SEC = 'شامل حداقل 8 کاراکتر';

const String FACE_ID_LOGIN = 'ورود با Face ID';
const String PASS_WORD_LOGIN = 'ورود با رمز';
const String LOGIN_SECURITY = 'امنیت ورود';
const String ENTER_PASS = 'رمز ورود وی‌بانک خود را وارد کنید';
const String RE_ENTER_PASS = 'رمز ورود خود را تکرار کنید';

const String UPDATE_PASS = 'رمز شما با موفقیت تغییر کرد.';
const String NOTIFICATION_SETTING = 'تنظیمات نحوه دریافت اعلانات';
const String NOTIFICATION_SETTING_LABEL = 'تنظیمات اعلانات';
const String SMS = 'پیامک';
const String EMPTY_NOTIFICATION = 'در حال حاضر هیچ اعلانی وجود ندارد.';
const String UPDATE = 'بروزرسانی';
const String LOG_OUT = 'خروج';
const String REFUSE = 'انصراف';
const String NEW_VERSION = 'آیا از بروزرسانی اطمینان دارید؟';
const String USER_LOGOUT_CAPTION = 'آبا مایل به خروج از حساب کاربری خود هستید؟';
const String NEW = 'جدید';
const String REFERRAL_CODE = 'کد معرف:';
const String YOUR_REFERRAL_CODE = 'کد معرف شما';
const String OTHER_REFERRAL_CODE = 'کد معرف دیگران';
const String DES_PHONE = 'شماره مقصد';
const String FRIEND_REFERRAL_CODE = 'کد معرف دوست خود را وارد کنید';
const String UPDATE_SUBMIT = 'تغییرات اعمال شد';
const String ENTER_DES_PHONE = 'شماره مقصد را وارد کنید';
const String SHARE = 'اشتراک‌ گذاری';
const String COPY_REFERRAL_CODE = 'کد معرف کپی شد.';
const String FRIEND_REFERRAL_CODE_SEND = 'کد معرف ثبت شد.';
const String SEND_REFERRAL_CODE = 'کد معرف شما با موفقیت ارسال شد.';
const String SEND_REFERRAL_CODE_FAIL = 'در حال حاضر امکان ارسال کد معرف شما وجود ندارد.';

const String NULL_HISTORY = 'تا به حال کرایه خودرو انجام نشده است.' ;
const String UNKNOWN = 'نا مشخص';
const String COLOR = 'رنگ:' ;
const String MODEL = 'مدل:' ;
const String CAR_BRAND ='برند و مدل خودرو:';
const String YEAR = 'سال ساخت:' ;